// Anti-AI Patterns — Based on Tsinghua PDF guidelines:
// PDF says "删除高度概括和冗余的词句", "少用鲜为人知的技术词汇"
// These patterns are common AI-generated filler phrases that should be detected
export const ZH_PATTERNS = [
  {
    id: 'zh-1',
    pattern: '值得注意的是',
    matchType: 'exact' as const,
    weight: 0.4,
    reason: 'AI 高频中文强调句式（清华手册：删除高度概括和冗余的词句）',
    lang: 'zh' as const,
  },
  {
    id: 'zh-2',
    pattern: '综上所述',
    matchType: 'exact' as const,
    weight: 0.3,
    reason: 'AI 高频总结连接词',
    lang: 'zh' as const,
  },
  {
    id: 'zh-3',
    pattern: '不难发现',
    matchType: 'exact' as const,
    weight: 0.3,
    reason: 'AI 高频推导过渡',
    lang: 'zh' as const,
  },
  {
    id: 'zh-4',
    pattern: '显而易见',
    matchType: 'exact' as const,
    weight: 0.3,
    reason: 'AI 高频断言式表达',
    lang: 'zh' as const,
  },
  {
    id: 'zh-5',
    pattern: '不言而喻',
    matchType: 'exact' as const,
    weight: 0.3,
    reason: 'AI 高频空话（清华手册：避免空话套话）',
    lang: 'zh' as const,
  },
  {
    id: 'zh-6',
    pattern: '研究的结果将会被讨论',
    matchType: 'exact' as const,
    weight: 0.5,
    reason: '清华手册明确指出应避免：需要写下结果以及为什么重要',
    lang: 'zh' as const,
  },
  {
    id: 'zh-7',
    pattern: '结果将会被',
    matchType: 'exact' as const,
    weight: 0.4,
    reason: '清华手册：避免"结果将会被讨论"式空话',
    lang: 'zh' as const,
  },
];

export const EN_PATTERNS = [
  {
    id: 'en-1',
    pattern: 'furthermore',
    matchType: 'exact' as const,
    weight: 0.3,
    reason: 'AI high-frequency connector',
    lang: 'en' as const,
  },
  {
    id: 'en-2',
    pattern: 'moreover',
    matchType: 'exact' as const,
    weight: 0.3,
    reason: 'AI high-frequency connector',
    lang: 'en' as const,
  },
  {
    id: 'en-3',
    pattern: 'notably',
    matchType: 'exact' as const,
    weight: 0.25,
    reason: 'AI high-frequency connector',
    lang: 'en' as const,
  },
  {
    id: 'en-4',
    pattern: 'it is important to note',
    matchType: 'exact' as const,
    weight: 0.4,
    reason: 'AI filler phrase (Tsinghua guide: remove redundant words)',
    lang: 'en' as const,
  },
  {
    id: 'en-5',
    pattern: 'additionally',
    matchType: 'exact' as const,
    weight: 0.25,
    reason: 'AI connector',
    lang: 'en' as const,
  },
  {
    id: 'en-6',
    pattern: 'consequently',
    matchType: 'exact' as const,
    weight: 0.2,
    reason: 'AI causal connector',
    lang: 'en' as const,
  },
  {
    id: 'en-7',
    pattern: 'results will be discussed',
    matchType: 'exact' as const,
    weight: 0.5,
    reason: 'Tsinghua guide: write the actual results and why they matter, not this vague phrase',
    lang: 'en' as const,
  },
  {
    id: 'en-8',
    pattern: 'it is worth noting',
    matchType: 'exact' as const,
    weight: 0.35,
    reason: 'AI filler phrase (Tsinghua guide: remove redundant words)',
    lang: 'en' as const,
  },
];
