blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/Gary23333/Scholarium/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
